# -*- coding: utf-8 -*-
"""Ai vission extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6OtLEbvSauZ4w0qR27P9C6lDJ1MctAJ
"""



!pip install pycocotools segmentation-models-pytorch albumentations gradio -q

!wget -c http://images.cocodataset.org/zips/val2017.zip
!unzip -q -o val2017.zip

!wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip
!unzip -q annotations_trainval2017.zip annotations/instances_val2017.json

"""# LOAD COCO"""

from pycocotools.coco import COCO

coco = COCO("annotations/instances_val2017.json")

img_ids = coco.getImgIds()

print("Total Images:", len(img_ids))

"""# CREATE BINARY SUBJECT MASK"""

import numpy as np

def create_binary_mask(image_id):

    ann_ids = coco.getAnnIds(imgIds=image_id)
    anns = coco.loadAnns(ann_ids)

    img_info = coco.loadImgs(image_id)[0]
    h, w = img_info['height'], img_info['width']

    mask = np.zeros((h,w))

    for ann in anns:
        mask += coco.annToMask(ann)

    return (mask > 0).astype(np.float32)

"""# DATASET + AUGMENTATION"""

import torch
from torch.utils.data import Dataset
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2

train_tf = A.Compose([
    A.Resize(320,320),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.4),
    A.Rotate(limit=25,p=0.5),
    A.GaussianBlur(p=0.2),
    A.Normalize(),
    ToTensorV2()
])

val_tf = A.Compose([
    A.Resize(320,320),
    A.Normalize(),
    ToTensorV2()
])

class CocoDataset(Dataset):

    def __init__(self, ids, tf):
        self.ids = ids
        self.tf = tf

    def __len__(self):
        return len(self.ids)

    def __getitem__(self, idx):

        img_id = self.ids[idx]
        info = coco.loadImgs(img_id)[0]

        image = np.array(Image.open(f"val2017/{info['file_name']}").convert("RGB"))
        mask = create_binary_mask(img_id)

        aug = self.tf(image=image, mask=mask)

        return aug['image'], aug['mask'].unsqueeze(0)

"""# TRAIN / VAL / TEST SPLIT"""

import random
from torch.utils.data import DataLoader

random.shuffle(img_ids)

n = len(img_ids)

train_ids = img_ids[:int(0.7*n)]
val_ids   = img_ids[int(0.7*n):int(0.85*n)]

train_loader = DataLoader(CocoDataset(train_ids, train_tf), batch_size=6, shuffle=True)
val_loader   = DataLoader(CocoDataset(val_ids, val_tf), batch_size=6)

"""# MODEL"""

import segmentation_models_pytorch as smp
import torch.nn as nn
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

model = smp.DeepLabV3Plus(
    encoder_name="resnet50",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1
).to(device)

bce = nn.BCEWithLogitsLoss()
dice = smp.losses.DiceLoss(mode="binary")

def loss_fn(pred, mask):
    return bce(pred,mask)+dice(pred,mask)

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)

"""# TRAIN LOOP"""

from tqdm import tqdm

def iou(pred, mask):
    pred = (pred>0.7).float()
    inter = (pred*mask).sum()
    union = pred.sum()+mask.sum()-inter
    return (inter+1e-6)/(union+1e-6)

best = 0

for epoch in range(15):

    model.train()
    total_loss = 0

    for img,mask in tqdm(train_loader):

        img,mask = img.to(device), mask.to(device)

        optimizer.zero_grad()
        out = model(img)

        loss = loss_fn(out,mask)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(),1.0)

        optimizer.step()
        total_loss += loss.item()

    model.eval()
    score = 0
    c = 0

    with torch.no_grad():
        for img,mask in val_loader:
            img,mask = img.to(device),mask.to(device)
            out = torch.sigmoid(model(img))
            score += iou(out,mask)
            c += 1

    score = (score/c).item()

    print(f"Epoch {epoch} Loss {total_loss:.3f} IoU {score:.4f}")

    if score > best:
        best = score
        torch.save(model.state_dict(),"best.pth")

"""# POST PROCESS CLEAN MASK"""

import cv2

def clean_mask(mask, smooth=5):

    mask = (mask*255).astype("uint8")

    numLabels, labels, stats, _ = cv2.connectedComponentsWithStats(mask)

    new_mask = np.zeros_like(mask)

    for i in range(1, numLabels):
        if stats[i, cv2.CC_STAT_AREA] > 500:
            new_mask[labels == i] = 255

    kernel = np.ones((7,7),np.uint8)

    new_mask = cv2.morphologyEx(new_mask, cv2.MORPH_CLOSE, kernel)
    new_mask = cv2.GaussianBlur(new_mask, (smooth,smooth), 0)

    return new_mask/255

"""# INFERENCE PIPELINE"""

def extract_subject(path, threshold=0.6, smooth=5, transparent=False):

    original = np.array(Image.open(path).convert("RGB"))
    H, W = original.shape[:2]

    small = cv2.resize(original, (320,320))
    tf = val_tf(image=small)
    tensor = tf['image'].unsqueeze(0).to(device)

    with torch.no_grad():
        pred = torch.sigmoid(model(tensor))

    mask = pred.cpu().squeeze().numpy()

    mask = np.where(mask > threshold, 1, 0).astype(np.uint8)

    mask = clean_mask(mask, smooth)

    mask = cv2.resize(mask, (W,H), interpolation=cv2.INTER_LINEAR)

    # ⭐ REMOVE HALO
    mask = cv2.erode(mask, np.ones((3,3),np.uint8), iterations=1)

    alpha = np.clip(mask, 0, 1)

    if transparent:
        rgba = np.dstack((original, (alpha*255).astype(np.uint8)))
        return rgba

    result = (original * alpha[..., None]).astype(np.uint8)

    return result

"""# GRADIO UI"""

import gradio as gr
import cv2

def ui_pipeline(image, threshold, smooth, transparent):

    cv2.imwrite("temp.jpg", image[:,:,::-1])

    result = extract_subject(
        "temp.jpg",
        threshold=threshold,
        smooth=int(smooth),
        transparent=transparent
    )

    return result

gr.Interface(
    fn=ui_pipeline,
    inputs=[
        gr.Image(type="numpy"),
        gr.Slider(0.3,0.9,value=0.7,step=0.05,label="Threshold"),
        gr.Slider(3,15,value=5,step=2,label="Smoothness"),
        gr.Checkbox(label="Transparent Background")
    ],
    outputs=gr.Image(type="numpy"),
    title="VisionExtract — Advanced Subject Isolation",
    description="Multi-subject | HD Output | Noise Removal | Adjustable Mask"
).launch()