# -*- coding: utf-8 -*-
"""vission extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jK_iWv1WQ_TjaypHAa86g9yk1-ZU0k8g
"""

!wget http://images.cocodataset.org/zips/val2017.zip
!unzip val2017.zip

"""**Acquire Dataset (COCO val2017)**"""

!wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip
!unzip annotations_trainval2017.zip annotations/instances_val2017.json

"""**Load COCO and Select Category**"""

from pycocotools.coco import COCO

annotation_file = "annotations/instances_val2017.json"
coco = COCO(annotation_file)

cat_ids = coco.getCatIds(catNms=['person'])
img_ids = coco.getImgIds(catIds=cat_ids)

print("Total person images:", len(img_ids))

"""**Explore Dataset Structure**"""

import os
print(len(os.listdir("val2017")))

"""file_name

height

width

id
"""

img_info = coco.loadImgs(img_ids[0])[0]
print(img_info)

"""**Visualize Example Image and Mask**"""

import numpy as np

def create_binary_mask(image_id):
    ann_ids = coco.getAnnIds(imgIds=image_id, catIds=cat_ids)
    anns = coco.loadAnns(ann_ids)

    img_info = coco.loadImgs(image_id)[0]
    height, width = img_info['height'], img_info['width']

    mask = np.zeros((height, width))

    for ann in anns:
        mask += coco.annToMask(ann)

    mask = (mask > 0).astype(np.float32)
    return mask

import matplotlib.pyplot as plt
from PIL import Image

img_id = img_ids[0]
img_info = coco.loadImgs(img_id)[0]
image = Image.open(f"val2017/{img_info['file_name']}")

mask = create_binary_mask(img_id)

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(image)

plt.subplot(1,2,2)
plt.title("Binary Mask")
plt.imshow(mask, cmap='gray')

plt.show()

"""**DATA PREPROCESSING & VALIDATION** ****
Develop Preprocessing Pipeline
"""

import torchvision.transforms as transforms

transform = transforms.Compose([
    transforms.Resize((256,256)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

"""*Ensure Image–Mask Alignment**
Image and mask must undergo same resize.
"""

from torch.utils.data import Dataset

class CocoSegmentationDataset(Dataset):
    def __init__(self, img_ids, image_dir, transform=None):
        self.img_ids = img_ids
        self.image_dir = image_dir
        self.transform = transform

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id = self.img_ids[idx]
        img_info = coco.loadImgs(img_id)[0]

        image = Image.open(f"{self.image_dir}/{img_info['file_name']}").convert("RGB")
        mask = create_binary_mask(img_id)

        mask = Image.fromarray(mask)

        if self.transform:
            image = self.transform(image)
            mask = transforms.Resize((256,256))(mask)
            mask = transforms.ToTensor()(mask)

        return image, mask

"""**Shuffle and Split (70/15/15)**"""

import random

random.seed(42)
random.shuffle(img_ids)

total = len(img_ids)
train_split = int(0.7 * total)
val_split = int(0.15 * total)

train_ids = img_ids[:train_split]
val_ids = img_ids[train_split:train_split+val_split]
test_ids = img_ids[train_split+val_split:]

"""**Create DataLoaders**"""

from torch.utils.data import DataLoader

train_dataset = CocoSegmentationDataset(train_ids, "val2017", transform)
val_dataset = CocoSegmentationDataset(val_ids, "val2017", transform)
test_dataset = CocoSegmentationDataset(test_ids, "val2017", transform)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False)

"""**Verify Alignment Visually**"""

image, mask = train_dataset[0]

plt.subplot(1,2,1)
plt.imshow(image.permute(1,2,0))

plt.subplot(1,2,2)
plt.imshow(mask.squeeze(), cmap='gray')

plt.show()

